# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:iGyAFYsC5GwrqgjRRk9HrdFeXGFd1fCYRsNPAs202X0=,iv:3kGy5V+z+pDHRHDQdEIWbAHXAL/ez3W7AUKdvkxWGmQ=,tag:zgpfPnTiy0SI8JLcYx6p6Q==,type:str]
sops:
  age:
    - recipient: age1qqrqa5eqkp6rr890jwc6htjdp96gdgph09rd5lmac5yklys89scssjm4xu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3YVEwdU9NcDVnV3d1bmwv
        QXdUcVRvSmQyYWg2VXZ3YmczQnhhdmNiTERzCm9nbWZYSXFnczFrYmFzR1VlVFNB
        MDI2VnZvS1Y3WHQ1cUhpMmJXNHVycncKLS0tIFBaRjRaVkFHeTdEZUZJK2hmTDZR
        SGNxeCtVS25KL1NpVXZEYzRLYXlETDQKwK2HhhDfhQKqvK/DR+mGKfU/dLG5QuV5
        hiv6u5J8d8yyt0Fa/X6o4X+E3CEOpmrPp1JULi6EmxsVKXicTpRVQA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-08T19:07:31Z"
  mac: ENC[AES256_GCM,data:K+sgm4RFfo/ZeNr7L0YEMvS1XlPf+AeqlcBubXHU+i8qe1AFN+TcCaWp4A9DgHwAbyQkStAwVuUavmIa0tOHdP9QyAZZPMfhDUIwaceRDP4fGzzD9/LU53kuqD44GaAQau1XoniLoK8lrvg0AcxxnbUEO1W2ccFxlIEsIZkAE+Q=,iv:x+KFygx+SEev2vcZUqh+OVqCRId2fW9L2rIaBbKW1Fg=,tag:7IdU4S80Tmcn0QTSGHkgmQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
