# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://192.168.0.200:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "192.168.0.200"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "k3s-manager-01"
    ipAddress: "192.168.0.21"
    installDiskSelector:
      serial: "nvme01/nm1"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/9i71nddfkdsd8j9skk2yobhobh9koyi13iikji0ymql5nsuq9sj7ugr78s1pjsk1
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "33:4b:1d:b1:ca:1e"
        dhcp: false
        addresses:
          - "192.168.0.21/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.0.1"
        mtu: 1500
        vip:
          ip: "192.168.0.200"

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/admission-controller-patch.yaml"
    - "@./patches/controller/cluster.yaml"

